name: Analyze code statically
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    env:
      ANALYZER: '@moneyforward/code-review-action-eslint-plugin'
      ANALYZER_VERSION: '~0'
      CI: true
    steps:
      - uses: actions/checkout@v2
      - run: sudo npm i -g --no-save "${ANALYZER}@${ANALYZER_VERSION}"
      - id: node-env
        run: echo "::set-output name=path::$(npm root -g)"
      - name: Analyze code statically
        uses: moneyforward/code-review-action@v0.1.0
        env:
          NODE_PATH: ${{ steps.node-env.outputs.path }}
        with:
          analyzer: ${{ env.ANALYZER }}
